version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deliverydb
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: deliverydb
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
